import SvgIcon, { type SvgIconProps } from '@mui/material/SvgIcon'

export interface BasesIconProps extends SvgIconProps {
  onFirst?: boolean
  onSecond?: boolean
  onThird?: boolean
}
// Generated by ChatGPT - edited by me to add home plate and align bases
export function BasesIcon({
  onFirst,
  onSecond,
  onThird,
  ...svgProps
}: BasesIconProps) {
  return (
    <SvgIcon viewBox="0 0 24 24" {...svgProps}>
      {/* Optional: Basepaths outline */}
       {/* home plate (bottom middle) */}
      <rect
        x={15}
        y={10}
        width={4}
        height={4}
        transform="rotate(45 8 11)"
        stroke="currentColor"
        strokeWidth={1.2}
        fill={'none'}
      />
      {/* Second base (top middle) */}
      <rect
        x={11}
        y={4}
        width={4}
        height={4}
        transform="rotate(45 13 6)"
        stroke="currentColor"
        strokeWidth={1.2}
        fill={onSecond ? 'currentColor' : 'none'}
      />

      {/* First base (bottom right) */}
      <rect
        x={15}
        y={8}
        width={4}
        height={4}
        transform="rotate(45 15 12)"
        stroke="currentColor"
        strokeWidth={1.2}
        fill={onFirst ? 'currentColor' : 'none'}
      />

      {/* Third base (bottom left) */}
      <rect
        x={7}
        y={10}
        width={4}
        height={4}
        transform="rotate(45 9 12)"
        stroke="currentColor"
        strokeWidth={1.2}
        fill={onThird ? 'currentColor' : 'none'}
      />
    </SvgIcon>
  )
}
